// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: specs/node.proto
#ifndef GRPC_specs_2fnode_2eproto__INCLUDED
#define GRPC_specs_2fnode_2eproto__INCLUDED

#include "node.pb.h"

#include <functional>
#include <grpcpp/generic/async_generic_service.h>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/client_context.h>
#include <grpcpp/completion_queue.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/rpc_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/support/stub_options.h>
#include <grpcpp/support/sync_stream.h>

namespace theminerzcoin {

class Node final {
 public:
  static constexpr char const* service_full_name() {
    return "theminerzcoin.Node";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status GetBlock(::grpc::ClientContext* context, const ::theminerzcoin::BlockRequest& request, ::theminerzcoin::BlockReply* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::theminerzcoin::BlockReply>> AsyncGetBlock(::grpc::ClientContext* context, const ::theminerzcoin::BlockRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::theminerzcoin::BlockReply>>(AsyncGetBlockRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::theminerzcoin::BlockReply>> PrepareAsyncGetBlock(::grpc::ClientContext* context, const ::theminerzcoin::BlockRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::theminerzcoin::BlockReply>>(PrepareAsyncGetBlockRaw(context, request, cq));
    }
    virtual ::grpc::Status BroadcastTransaction(::grpc::ClientContext* context, const ::theminerzcoin::RawTransaction& request, ::theminerzcoin::BroadcastReply* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::theminerzcoin::BroadcastReply>> AsyncBroadcastTransaction(::grpc::ClientContext* context, const ::theminerzcoin::RawTransaction& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::theminerzcoin::BroadcastReply>>(AsyncBroadcastTransactionRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::theminerzcoin::BroadcastReply>> PrepareAsyncBroadcastTransaction(::grpc::ClientContext* context, const ::theminerzcoin::RawTransaction& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::theminerzcoin::BroadcastReply>>(PrepareAsyncBroadcastTransactionRaw(context, request, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      virtual void GetBlock(::grpc::ClientContext* context, const ::theminerzcoin::BlockRequest* request, ::theminerzcoin::BlockReply* response, std::function<void(::grpc::Status)>) = 0;
      virtual void GetBlock(::grpc::ClientContext* context, const ::theminerzcoin::BlockRequest* request, ::theminerzcoin::BlockReply* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      virtual void BroadcastTransaction(::grpc::ClientContext* context, const ::theminerzcoin::RawTransaction* request, ::theminerzcoin::BroadcastReply* response, std::function<void(::grpc::Status)>) = 0;
      virtual void BroadcastTransaction(::grpc::ClientContext* context, const ::theminerzcoin::RawTransaction* request, ::theminerzcoin::BroadcastReply* response, ::grpc::ClientUnaryReactor* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::theminerzcoin::BlockReply>* AsyncGetBlockRaw(::grpc::ClientContext* context, const ::theminerzcoin::BlockRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::theminerzcoin::BlockReply>* PrepareAsyncGetBlockRaw(::grpc::ClientContext* context, const ::theminerzcoin::BlockRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::theminerzcoin::BroadcastReply>* AsyncBroadcastTransactionRaw(::grpc::ClientContext* context, const ::theminerzcoin::RawTransaction& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::theminerzcoin::BroadcastReply>* PrepareAsyncBroadcastTransactionRaw(::grpc::ClientContext* context, const ::theminerzcoin::RawTransaction& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    ::grpc::Status GetBlock(::grpc::ClientContext* context, const ::theminerzcoin::BlockRequest& request, ::theminerzcoin::BlockReply* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::theminerzcoin::BlockReply>> AsyncGetBlock(::grpc::ClientContext* context, const ::theminerzcoin::BlockRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::theminerzcoin::BlockReply>>(AsyncGetBlockRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::theminerzcoin::BlockReply>> PrepareAsyncGetBlock(::grpc::ClientContext* context, const ::theminerzcoin::BlockRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::theminerzcoin::BlockReply>>(PrepareAsyncGetBlockRaw(context, request, cq));
    }
    ::grpc::Status BroadcastTransaction(::grpc::ClientContext* context, const ::theminerzcoin::RawTransaction& request, ::theminerzcoin::BroadcastReply* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::theminerzcoin::BroadcastReply>> AsyncBroadcastTransaction(::grpc::ClientContext* context, const ::theminerzcoin::RawTransaction& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::theminerzcoin::BroadcastReply>>(AsyncBroadcastTransactionRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::theminerzcoin::BroadcastReply>> PrepareAsyncBroadcastTransaction(::grpc::ClientContext* context, const ::theminerzcoin::RawTransaction& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::theminerzcoin::BroadcastReply>>(PrepareAsyncBroadcastTransactionRaw(context, request, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void GetBlock(::grpc::ClientContext* context, const ::theminerzcoin::BlockRequest* request, ::theminerzcoin::BlockReply* response, std::function<void(::grpc::Status)>) override;
      void GetBlock(::grpc::ClientContext* context, const ::theminerzcoin::BlockRequest* request, ::theminerzcoin::BlockReply* response, ::grpc::ClientUnaryReactor* reactor) override;
      void BroadcastTransaction(::grpc::ClientContext* context, const ::theminerzcoin::RawTransaction* request, ::theminerzcoin::BroadcastReply* response, std::function<void(::grpc::Status)>) override;
      void BroadcastTransaction(::grpc::ClientContext* context, const ::theminerzcoin::RawTransaction* request, ::theminerzcoin::BroadcastReply* response, ::grpc::ClientUnaryReactor* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::theminerzcoin::BlockReply>* AsyncGetBlockRaw(::grpc::ClientContext* context, const ::theminerzcoin::BlockRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::theminerzcoin::BlockReply>* PrepareAsyncGetBlockRaw(::grpc::ClientContext* context, const ::theminerzcoin::BlockRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::theminerzcoin::BroadcastReply>* AsyncBroadcastTransactionRaw(::grpc::ClientContext* context, const ::theminerzcoin::RawTransaction& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::theminerzcoin::BroadcastReply>* PrepareAsyncBroadcastTransactionRaw(::grpc::ClientContext* context, const ::theminerzcoin::RawTransaction& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_GetBlock_;
    const ::grpc::internal::RpcMethod rpcmethod_BroadcastTransaction_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status GetBlock(::grpc::ServerContext* context, const ::theminerzcoin::BlockRequest* request, ::theminerzcoin::BlockReply* response);
    virtual ::grpc::Status BroadcastTransaction(::grpc::ServerContext* context, const ::theminerzcoin::RawTransaction* request, ::theminerzcoin::BroadcastReply* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_GetBlock : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_GetBlock() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_GetBlock() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetBlock(::grpc::ServerContext* /*context*/, const ::theminerzcoin::BlockRequest* /*request*/, ::theminerzcoin::BlockReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGetBlock(::grpc::ServerContext* context, ::theminerzcoin::BlockRequest* request, ::grpc::ServerAsyncResponseWriter< ::theminerzcoin::BlockReply>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_BroadcastTransaction : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_BroadcastTransaction() {
      ::grpc::Service::MarkMethodAsync(1);
    }
    ~WithAsyncMethod_BroadcastTransaction() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status BroadcastTransaction(::grpc::ServerContext* /*context*/, const ::theminerzcoin::RawTransaction* /*request*/, ::theminerzcoin::BroadcastReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestBroadcastTransaction(::grpc::ServerContext* context, ::theminerzcoin::RawTransaction* request, ::grpc::ServerAsyncResponseWriter< ::theminerzcoin::BroadcastReply>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_GetBlock<WithAsyncMethod_BroadcastTransaction<Service > > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_GetBlock : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_GetBlock() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::theminerzcoin::BlockRequest, ::theminerzcoin::BlockReply>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::theminerzcoin::BlockRequest* request, ::theminerzcoin::BlockReply* response) { return this->GetBlock(context, request, response); }));}
    void SetMessageAllocatorFor_GetBlock(
        ::grpc::MessageAllocator< ::theminerzcoin::BlockRequest, ::theminerzcoin::BlockReply>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::theminerzcoin::BlockRequest, ::theminerzcoin::BlockReply>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_GetBlock() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetBlock(::grpc::ServerContext* /*context*/, const ::theminerzcoin::BlockRequest* /*request*/, ::theminerzcoin::BlockReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* GetBlock(
      ::grpc::CallbackServerContext* /*context*/, const ::theminerzcoin::BlockRequest* /*request*/, ::theminerzcoin::BlockReply* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_BroadcastTransaction : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_BroadcastTransaction() {
      ::grpc::Service::MarkMethodCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::theminerzcoin::RawTransaction, ::theminerzcoin::BroadcastReply>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::theminerzcoin::RawTransaction* request, ::theminerzcoin::BroadcastReply* response) { return this->BroadcastTransaction(context, request, response); }));}
    void SetMessageAllocatorFor_BroadcastTransaction(
        ::grpc::MessageAllocator< ::theminerzcoin::RawTransaction, ::theminerzcoin::BroadcastReply>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(1);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::theminerzcoin::RawTransaction, ::theminerzcoin::BroadcastReply>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_BroadcastTransaction() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status BroadcastTransaction(::grpc::ServerContext* /*context*/, const ::theminerzcoin::RawTransaction* /*request*/, ::theminerzcoin::BroadcastReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* BroadcastTransaction(
      ::grpc::CallbackServerContext* /*context*/, const ::theminerzcoin::RawTransaction* /*request*/, ::theminerzcoin::BroadcastReply* /*response*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_GetBlock<WithCallbackMethod_BroadcastTransaction<Service > > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_GetBlock : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_GetBlock() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_GetBlock() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetBlock(::grpc::ServerContext* /*context*/, const ::theminerzcoin::BlockRequest* /*request*/, ::theminerzcoin::BlockReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_BroadcastTransaction : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_BroadcastTransaction() {
      ::grpc::Service::MarkMethodGeneric(1);
    }
    ~WithGenericMethod_BroadcastTransaction() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status BroadcastTransaction(::grpc::ServerContext* /*context*/, const ::theminerzcoin::RawTransaction* /*request*/, ::theminerzcoin::BroadcastReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_GetBlock : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_GetBlock() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_GetBlock() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetBlock(::grpc::ServerContext* /*context*/, const ::theminerzcoin::BlockRequest* /*request*/, ::theminerzcoin::BlockReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGetBlock(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_BroadcastTransaction : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_BroadcastTransaction() {
      ::grpc::Service::MarkMethodRaw(1);
    }
    ~WithRawMethod_BroadcastTransaction() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status BroadcastTransaction(::grpc::ServerContext* /*context*/, const ::theminerzcoin::RawTransaction* /*request*/, ::theminerzcoin::BroadcastReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestBroadcastTransaction(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_GetBlock : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_GetBlock() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->GetBlock(context, request, response); }));
    }
    ~WithRawCallbackMethod_GetBlock() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetBlock(::grpc::ServerContext* /*context*/, const ::theminerzcoin::BlockRequest* /*request*/, ::theminerzcoin::BlockReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* GetBlock(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_BroadcastTransaction : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_BroadcastTransaction() {
      ::grpc::Service::MarkMethodRawCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->BroadcastTransaction(context, request, response); }));
    }
    ~WithRawCallbackMethod_BroadcastTransaction() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status BroadcastTransaction(::grpc::ServerContext* /*context*/, const ::theminerzcoin::RawTransaction* /*request*/, ::theminerzcoin::BroadcastReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* BroadcastTransaction(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_GetBlock : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_GetBlock() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::theminerzcoin::BlockRequest, ::theminerzcoin::BlockReply>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::theminerzcoin::BlockRequest, ::theminerzcoin::BlockReply>* streamer) {
                       return this->StreamedGetBlock(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_GetBlock() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status GetBlock(::grpc::ServerContext* /*context*/, const ::theminerzcoin::BlockRequest* /*request*/, ::theminerzcoin::BlockReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedGetBlock(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::theminerzcoin::BlockRequest,::theminerzcoin::BlockReply>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_BroadcastTransaction : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_BroadcastTransaction() {
      ::grpc::Service::MarkMethodStreamed(1,
        new ::grpc::internal::StreamedUnaryHandler<
          ::theminerzcoin::RawTransaction, ::theminerzcoin::BroadcastReply>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::theminerzcoin::RawTransaction, ::theminerzcoin::BroadcastReply>* streamer) {
                       return this->StreamedBroadcastTransaction(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_BroadcastTransaction() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status BroadcastTransaction(::grpc::ServerContext* /*context*/, const ::theminerzcoin::RawTransaction* /*request*/, ::theminerzcoin::BroadcastReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedBroadcastTransaction(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::theminerzcoin::RawTransaction,::theminerzcoin::BroadcastReply>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_GetBlock<WithStreamedUnaryMethod_BroadcastTransaction<Service > > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_GetBlock<WithStreamedUnaryMethod_BroadcastTransaction<Service > > StreamedService;
};

}  // namespace theminerzcoin


#endif  // GRPC_specs_2fnode_2eproto__INCLUDED
