repos:
  - repo: https://github.com/pre-commit/mirrors-clang-format
    rev: v18.1.0
    hooks:
      - id: clang-format
        files: '\.(cpp|h)$'

  - repo: local
    hooks:
      - id: rustfmt
        name: rustfmt
        entry: rustfmt
        language: system
        types: [rust]
      - id: cargo-fmt-check
        name: cargo fmt --check
        entry: cargo fmt --manifest-path rust/Cargo.toml -- --check
        language: system
        pass_filenames: false
        files: '^rust/'
