.PHONY: FORCE
all: FORCE
	$(MAKE) -C .. theminerzcoin_qt test_theminerzcoin_qt
clean: FORCE
	$(MAKE) -C .. theminerzcoin_qt_clean test_theminerzcoin_qt_clean
check: FORCE
	$(MAKE) -C .. test_theminerzcoin_qt_check
theminerzcoin-qt theminerzcoin-qt.exe: FORCE
	 $(MAKE) -C .. theminerzcoin_qt
