openapi: 3.1.0
info:
  title: TheMinerzCoin RPC API
  version: "3.0.0"
paths:
  /getblockchaininfo:
    get:
      summary: Get blockchain info
      responses:
        '200':
          description: blockchain info
  /getblock/{hash}:
    get:
      summary: Get block details
      parameters:
        - name: hash
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: block data
  /sendtoaddress:
    post:
      summary: Send coins to address
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                address:
                  type: string
                amount:
                  type: number
      responses:
        '200':
          description: transaction id
  /wallet/create:
    post:
      summary: Create a new wallet
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
      responses:
        '200':
          description: wallet created
  /wallet/{name}/balance:
    get:
      summary: Get wallet balance
      parameters:
        - name: name
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: wallet balance
  /staking/delegate:
    post:
      summary: Delegate stake
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                address:
                  type: string
                amount:
                  type: number
      responses:
        '200':
          description: delegation tx id
  /staking/status:
    get:
      summary: Get staking status
      responses:
        '200':
          description: staking status
  /network/stats:
    get:
      summary: Get network statistics
      responses:
        '200':
          description: network statistics
