openapi: 3.1.0
info:
  title: TheMinerzCoin RPC API
  version: "3.0.0"
  description: Specification for TheMinerzCoin RPC interface version 3.0.0.
servers:
  - url: http://localhost:8332/
    description: Default RPC endpoint
paths:
  /getblockchaininfo:
    get:
      summary: Get blockchain info
      responses:
        '200':
          description: blockchain info
  /getblock/{hash}:
    get:
      summary: Get block details
      parameters:
        - name: hash
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: block data
  /sendtoaddress:
    post:
      summary: Send coins to address
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                address:
                  type: string
                amount:
                  type: number
      responses:
        '200':
          description: transaction id
  /wallet/create:
    post:
      summary: Create a new wallet
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
      responses:
        '200':
          description: wallet created
  /wallet/importdescriptors:
    post:
      summary: Import descriptors
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: array
      responses:
        '200':
          description: import result
  /wallet/{name}/balance:
    get:
      summary: Get wallet balance
      parameters:
        - name: name
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: wallet balance
  /walletcreatefundedpsbt:
    post:
      summary: Create and fund PSBT v2
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
      responses:
        '200':
          description: funded PSBT
  /staking/delegate:
    post:
      summary: Delegate stake
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                address:
                  type: string
                amount:
                  type: number
      responses:
        '200':
          description: delegation tx id
  /staking/status:
    get:
      summary: Get staking status
      responses:
        '200':
          description: staking status
  /network/stats:
    get:
      summary: Get network statistics
      responses:
        '200':
          description: network statistics
  /getslashinginfo:
    get:
      summary: Get slashed validator information
      responses:
        '200':
          description: slashing info
  /enumeratehw:
    get:
      summary: List connected hardware wallets
      responses:
        '200':
          description: hardware wallets
  /sendtohw:
    post:
      summary: Send raw APDU to hardware wallet
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                path:
                  type: string
                data:
                  type: string
      responses:
        '200':
          description: send result
  /metrics:
    get:
      summary: Prometheus metrics
      responses:
        '200':
          description: metrics output
          content:
            text/plain:
              schema:
                type: string
