name: build
on: [push, pull_request]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-2022, macos-14]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Cache Conan
        uses: actions/cache@v3
        with:
          path: ~/.conan2
          key: ${{ runner.os }}-conan-${{ hashFiles('conanfile.py') }}
          restore-keys: ${{ runner.os }}-conan-
      - name: Install dependencies
        run: |
          conan profile detect --force
          conan install . --output-folder=build --build=missing
      - name: Configure
        run: cmake -S . -B build -DWITH_GUI=OFF -DWITH_RUST=OFF
      - name: Build
        run: cmake --build build -j2
      - name: Package
        run: cmake --build build --target package
      - uses: actions/upload-artifact@v3
        with:
          name: ${{ runner.os }}-artifacts
          path: build/**/*
